---
  - name: Create machine
    ec2:
      aws_access_key: "{{aws_access_key_id}}"
      aws_secret_key: "{{aws_secret_access_key}}"
      key_name: "{{key_name}}"
      vpc_subnet_id: "{{subnet_id}}"
      instance_type: "{{instance_type}}"
      image: "{{image}}"
      region: "{{region}}"
      wait: yes
      group: lab-machine-sg
      exact_count: "{{instances}}"
      count_tag:
        Role: "lab"
        Name: "lab_machine"
      assign_public_ip: yes
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 15
          delete_on_termination: true
      instance_tags:
        Name: "lab_machine"
        Role: "lab"
    register: ec2


  - name: Add instances to host group
    add_host: hostname={{item.public_ip}} groupname={{ec2_group_name}}
    with_items: '{{ec2.instances}}'
